---
- name: Konfigurera användare och rättigheter på filservern
  hosts: all
  become: yes
  tasks:
    - name: Skapa Grupp A och Grupp B
      group:
        name: "{{ item }}"
        state: present
      loop:
        - grupp_a
        - grupp_b

    - name: Skapa testanvändaren Jacob i Grupp A
      user:
        name: jacob_a
        group: grupp_a
        password: "test123"
        
    - name: Sätt rättigheter på Avdelning A (Bara Grupp A får komma in)
      file:
        path: /shares/avdelning-a
        owner: root      # <--- Ägare
        group: grupp_a   # <--- Grupptillhörighet
        mode: '0770'     # <--- Hur mycket tillgång (7=allt, 0=inget)

    - name: Sätt rättigheter på Avdelning B (Bara Grupp B får komma in)
      file:
        path: /shares/avdelning-b
        owner: root
        group: grupp_b
        mode: '0770'
        